# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 22:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20160408_0348'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user_profile',
            managers=[
            ],
        ),
    ]
