# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 04:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20160408_0348'),
        ('imager_images', '0003_auto_20160412_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('date_uploaded', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('date_published', models.DateField()),
                ('published', models.CharField(choices=[('PRIV', 'Private'), ('SHARE', 'Shared'), ('PUBLIC', 'Public')], default='PUBLIC', max_length=6)),
                ('cover', models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='cover', to='imager_images.Photo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imager_profile.User_Profile')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='imager_images.Album'),
        ),
    ]
