# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20160412_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='album',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
