# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0006_auto_20160413_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='imager_profile.User_Profile'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='imager_profile.User_Profile'),
        ),
    ]
